#!/usr/bin/env bash

#Configures a new Nginx server
sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.ngix-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/jossvega103 permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
