#!/usr/bin/env bash

filename="/var/run/myscript.pid"

sudo echo "$$" >> $filename

trap 'echo "I hate the kill command" && exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'exit' SIGQUIT

while true; do

	echo "To infinity and beyond"
	sleep 2
done
