#!/usr/bin/env bash
#prints the time
Hour=0
minutes=1

while [ "$Hour" -le 12 ]; do

	echo "Hour: $Hour"

	while [ "$minutes" -ne 60 ]; do

		echo "$minutes"
		((minutes++))
	done

	((Hour++))
	minutes=1
done
